fix: base64 encoding of the GCP Service Account Key

diff --git a/gcp/biganimal-csp-setup b/gcp/biganimal-csp-setup
--- a/gcp/biganimal-csp-setup
+++ b/gcp/biganimal-csp-setup
@@ -67,7 +67,7 @@ show_help()
   echo "  or equivalents like"
   echo "  roles/owner"
   echo "Required tools:"
-  echo "  jq"
+  echo "  jq, base64"
   echo "Usage:"
   echo -e "  ${GREEN}$0 -p GCP_PROJECT_ID [options]${NC}"
   echo ""
@@ -92,6 +92,8 @@ check()
   check_gcloud_version
   # jq is required.
   hash jq > /dev/null 2>&1 || { show_help; echo -e "${RED}Error: please install jq on the system${NC}"; }
+  # base64 is required.
+  hash base64 > /dev/null 2>&1 || { show_help; echo -e "${RED}Error: please install base64 on the system${NC}"; }
   check_project
   check_names
 }
@@ -257,7 +259,7 @@ create_service_account()
   sa_key_id=$(gcloud iam service-accounts keys list --project "$project" \
     --iam-account "${service_account_id}" --managed-by user --format json | jq -r '.[0].name')
   # getting the escaped JSON string of the key to be saved later into "ba-passport.json"
-  sa_key=$(jq -cj . "${CURRENT_PATH}"/biganimal_serviceaccount_key.json | jq -R -s)
+  sa_key=$(base64 -w0 < "${CURRENT_PATH}"/biganimal_serviceaccount_key.json)
 }
 
 save_result()
@@ -271,7 +273,7 @@ save_result()
   echo -e "Created GCP service account ${GREEN}biganimal-${suffix_sa_name}${NC}"
   echo -e "Created GCP service account key, ID is ${GREEN}${sa_key_id##*/}${NC}"
   # exporting JSON "ba-passport.json" that will be used by BigAnimal CLI
-  echo "{\"gcpProject\":\"${project}\", \"roleName\":\"biganimal_${suffix_role_name}\", \"serviceAccountName\":\"biganimal-${suffix_sa_name}\",\"serviceAccountKey\":${sa_key}}" > "$CURRENT_PATH"/ba-passport.json
+  echo "{\"gcpProject\":\"${project}\", \"roleName\":\"biganimal_${suffix_role_name}\", \"serviceAccountName\":\"biganimal-${suffix_sa_name}\",\"serviceAccountKey\":\"${sa_key}\"}" > "$CURRENT_PATH"/ba-passport.json
 }
 
 check
