fix: check for needed GCP gcloud config prerequisites

diff --git a/gcp/biganimal-csp-setup b/gcp/biganimal-csp-setup
--- a/gcp/biganimal-csp-setup
+++ b/gcp/biganimal-csp-setup
@@ -92,6 +92,22 @@ check()
   #### Check gcloud CLI version
   check_gcloud_version
   # jq is required.
+  #### Check gcloud auth
+    gcloud_auth_list=$(gcloud auth list --format json | jq -r '.[] | select(.status=="ACTIVE").account | length')
+    if [ "$gcloud_auth_list" -eq 0 ]; then
+      show_help
+      echo -e "${RED}Error: no GCP account ACTIVE in gcloud CLI${NC}"
+      echo -e "${RED}Please run 'gcloud auth login' to login to your GCP account${NC}"
+      exit 1
+    fi
+    #### Check gcloud account set
+    gcloud_account_set=$(gcloud config configurations list --format json | jq -r '.[] | select(.is_active==true).properties.core.account | length')
+    if [ "$gcloud_account_set" -eq 0 ]; then
+      show_help
+      echo -e "${RED}Error: no GCP account set in gcloud CLI${NC}"
+      echo -e "${RED}Please run 'gcloud config set account YOUR_GCP_EMAIL_ACCOUNT' to set the GCP account${NC}"
+      exit 1
+    fi
   hash jq > /dev/null 2>&1 || { show_help; echo -e "${RED}Error: please install jq on the system${NC}"; }
   # base64 is required.
   hash base64 > /dev/null 2>&1 || { show_help; echo -e "${RED}Error: please install base64 on the system${NC}"; }
